version: "3.9"

services:
  hdymonitor:
    image: ghcr.io/aiqinxauncai/hdymonitor:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RUN_INTERVAL_SECONDS: "300"
      TARGET_URL: "https://www.szhdy.com/activities/default.html?method=activity&id=11"
      STORAGE_PATH: "/data/lastServers.json"
      PUSHDEER_KEY: ""
      ALIYUNAPI_KEY: ""
      ALIYUNAPI_SECRET: ""
    volumes:
      - ./data:/data
    restart: unless-stopped
