version: "3.9"

services:
  hdymonitor:
    image: ghcr.io/aiqinxauncai/hdymonitor:latest
    environment:
      RUN_INTERVAL_SECONDS: "300"
      TARGET_URL: "https://www.szhdy.com/activities/default.html?method=activity&id=11"
      STORAGE_PATH: "/data/lastServers.json"
      CONFIG_ID_MONITOR_ENABLED: "true"
      CONFIG_ID_URL_TEMPLATE: "https://www.szhdy.com/cart?action=configureproduct&pid={id}"
      CONFIG_ID_START: "2018"
      CONFIG_ID_BACKWARD_SCAN_LIMIT: "200"
      CONFIG_ID_STORAGE_PATH: "/data/lastConfigId.json"
      PUSHDEER_KEY: "" # 支持多个，使用英文逗号/分号/空格分隔
      ALIYUNAPI_KEY: ""
      ALIYUNAPI_SECRET: ""
    volumes:
      - ./data:/data
    restart: unless-stopped
